---
title: "Font Embedding for LaTeX and R users"
subtitle: "Use cairo_pdf()"
author: "Hansjörg Plieninger"
date: "2018-01-30"
slug: font-encoding-for-latex-and-r-users
draft: true
categories: []
tags: [R, LaTeX, pdf, note-to-myself]
---

## Motivation

Recently, I sent my disseratation as a PDF file to a copy shop and got an email back that I had not embedded all fonts and that they won't print it for me. What? So instead of celebrating the submission, I had to search online for `pdf latex "font embedding"`, and this blog post is a summary of that afternoon.

## Embedding Fonts in PDFs

Embedding fonts is probably not cruciual for non-exotic fonts on non-exotic devices/printers. However, if you wish that your PDF is correctly displayed or printed on any possible device, fonts should be embedded. Such devices could be, for example, a printer of a copy shop, an exotic PDF reader of a student, or a person with an otherwise different setup (e.g., someone in the year 2076 or someone in Tanzania).

## Why

In order to use (i.e., display or print) a PDF, the system has to know which fonts it should use.

* If the font used in the PDF is available on the system, it is able to handle it correctly (e.g., Arial).
* If the font used in the PDF is not available on the system but is embedded in the PDF, the system is able to handle it correctly.
* If the font is not available and not embedded, the system will guess what font to use for display/print and this may or may not work. This [link](http://wiki.opf-labs.org/download/attachments/101613571/fonts_notembedded.jpg?version=1&modificationDate=1430223649000) shows an extreme example of what might happen.

Thus, one should always embed fonts. This will ensure that the PDF will be correctly displayed/printed on any device at any time.


## Problem: R does not embed fonts

R does not embed fonts when producing a PDF via `pdf()`. Thus, if you compile a PDF with LaTeX and include R plots (i.e., PDFs), LaTeX cannot embed the fonts of the plots, and then you finally have a PDF with some fonts not embedded. LaTeX itself seems to embed all fonts automatically, so if you don't include any plots, you don't have to worry.

You can check whether fonts are embedded with any PDF reader and something along the lines of Properties -> Fonts.


## Solution in R: Use `cairo_pdf()`

* Do not produce vector graphics via `pdf()` but images via, for example, `png()`. This is probably not the desired solution because of quality, but it should work.
* Produce vector graphics not via `pdf()` but via `cairo_pdf()`. This will embed the fonts automatically, and LaTeX will subsequently embed these fonts, too.
* Producing some sort of postscript, EPS, or whatever (I dont't have a clue), will probably work as well.
* You may also embed fonts post hoc using the R package **extrafont** and its functionality of embedding fonts, e.g., `extrafont::embed_fonts("f1.pdf", outfile="f1_embed.pdf")`.  
BTW: You may use any font (available on your system) in any R plot with the **extrafont** package. This allows, for example, to use standard LaTeX font Computer Modern in R plots (looks ugly, of course).


## Solution With Finished PDF

If you already have a PDF with unembedded fonts and want to embed the fonts post hoc, things are different and may be a bit more difficult. What worked for me in a one or two test cases are the following solutions.

* Use the **extrafont** R package and its function `embed_fonts()` as stated above.
* Use ghostscript as described in the following blog post, close to the end of the post. What worked for me is the following command in a Windows Command Prompt
	
```{r, eval = F}
gswin64c -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -dEmbedAllFonts=true -sOutputFile=C:\...\my_plot_embedded.pdf -f C:\...\my_plot.pdf
```

These solutions are certainly dependent on the fact that you have the fonts, which you want to embed, installed on your computer.
